# Generated by Django 5.0.1 on 2024-02-26 09:54

import crmApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('role', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('profile_photo', models.ImageField(blank=True, upload_to='images/', validators=[crmApp.models.validate_picture_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])])),
            ],
        ),
    ]
